### ISSUE TITLE
Diffuse textures not in material - Chronicles X

### ISSUE THREAD

**Issue by 09williamsad** [PredatorCZ/XenoMax#11]
XenoMax V1.2
Windows 10 64 bit
3ds max 2018 64 bit 20.0.0.966
Xenoblade Chronicles X 

When importing a camdo model the material is missing the diffuse texture but has the normal, specular, emissive ect textures.
The diffuse texture is included in the export but is not referenced in the material.
I have tried a number of the chr models, all so far has this issue.

Sample in original, 3ds max and fbx https://mega.nz/file/eewHwaTQ#QP7Z9rdR2HcUhYyhgE3VDQhM6ygeqiv7zQ6JbVQZmB8

**Comment by keesoudwater34** [comment]
thats something at least ive experienced aswell. most the time the diffuse gets modified ingame so i dont know if that has anything to do with it. and not to mention the skells are wierd on their own but its workable. just small cleanup

**Comment by PredatorCZ** [comment]
If the tool doesn't know, where to put the texture in material, it will put them into Composite Map, and link it to a Ambient Color on the material.
I strongly advise you to use node editor instead of composite one, so you can see textures and relink them by hand.
You must ALWAYS relink textures stored in Composite Map into correct slots in material, or compose them together, for example masks and albedo, normal map blend, etc.. This is entirely up to you, since I cannot read shaders, but it's completely manageable without them.
